### ISSUE TITLE
Prints are showing up as books

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#130]
The following objects by the same person, Israël Silvestre 

bdr:381057, bdr:381060,  bdr:381063, bdr:381066, bdr:381069, bdr:381072, bdr:381075, bdr:381078, bdr:381081, bdr:381084, bdr:381087, bdr:381090

are all showing up as books and not as prints. This seems to be because they have 2 images associated with each object. The 2nd image is the back of the print, i think. or maybe a folder over. 

How can we identify them as prints so they show up on the correct page? If we are looking for 1 page objects, this won't work. They appear to have this in the metadata:
&lt;mods:form authority="marcform">print&lt;/mods:form> but the books do as well.

**Comment by emylonas** [comment]
I am re-assigning to Joseph because this is at the moment more of an information question. 

Is there a way to figure out is something is a print and not a book from the metadata? I can ask Ann as well.

**Comment by emylonas** [comment]
From Ann Caldwell:
The <mods:form> refers to the "A designation of a particular physical presentation of a resource, including the physical form or medium of material for a resource" and is derived from a MARC 008 field saying it is a print format vs. non-print format. So by saying it's print, it could be a book, score, mixed media, print serial. 

The only MODS records that have that are the ones that are derived from MARC records--it isn't a genre field and has absolutely nothing to do a specific description of the item

I'm looking at bdr:381057--the genre is engravings (prints) which is the legitimate AAT genre. If you're looking to sort items by what they are you should be looking at the <mods:genre>

**Comment by emylonas** [comment]
re-assigning to Carlos who may be able to work with information in comment above. Perhaps useful to check first if the set of what we think are books is the same as the set of things that have &lt;mods:genre authority="aat">books&lt;mods:genre>

Also, is this indexed?

**Comment by bcail** [comment]
Yes, mods:form is indexed: mods_physicalDescription_form_ssim (for bdr:381057). This was just added, so it may not be indexed for all objects yet, but I'm in the process of re-indexing everything in the BDR. (mods:genre is also indexed: mods_genre_aat_ssim or genre.)

**Comment by crotger** [comment]
Right now the searches we do for prints and books are based on object_type. There are 77 things that show up as 'books', (have an object_type of implicit-set). 61 of them have a genre of 'books', and of there are 16 that don't:

__the 12 prints Elli identified by Silvestre and with a genre of "engravings (prints)"__
*  bdr:381057 [https://library.brown.edu/projects/rome/books/381057]
*  bdr:381060 [https://library.brown.edu/projects/rome/books/381060]
*  bdr:381063 [https://library.brown.edu/projects/rome/books/381063]
*  bdr:381066 [https://library.brown.edu/projects/rome/books/381066]
*  bdr:381069 [https://library.brown.edu/projects/rome/books/381069]
*  bdr:381072 [https://library.brown.edu/projects/rome/books/381072]
*  bdr:381075 [https://library.brown.edu/projects/rome/books/381075]
*  bdr:381078 [https://library.brown.edu/projects/rome/books/381078]
*  bdr:381081 [https://library.brown.edu/projects/rome/books/381081]
*  bdr:381084 [https://library.brown.edu/projects/rome/books/381084]
*  bdr:381087 [https://library.brown.edu/projects/rome/books/381087]
*  bdr:381090 [https://library.brown.edu/projects/rome/books/381090]  


__Four books not by Silvestre__
*  bdr:382871 [https://library.brown.edu/projects/rome/books/382871]
  * etchings
*  bdr:252240 [https://library.brown.edu/projects/rome/books/252240]
  * (doesn't have a genre)
*  bdr:240510 [https://library.brown.edu/projects/rome/books/240510]
  * engravings (prints)
*  bdr:317982 [https://library.brown.edu/projects/rome/books/317982]
  * engravings (prints)


We could switch to using genre to get results rather than object_type, but we'd have to deal with these four. Two of them have a significant amount of text in them, and the other two are just images.

**Comment by crotger** [comment]
When I look for top-level items with genre "etchings" "engravings", "etchings (prints)" or "engravings (prints)", I get 126 results:

* Our 108 prints (all object_type: image-compound)
* The 15 books with different genres from my previous comment (12 Silvestre prints + 3 other books + 1 without a genre = 16)
* 3 jp2 objects that look like prints but don't show up anywhere on the TTWR site ([bdr:381668](https://repository.library.brown.edu/studio/item/bdr:381668), [bdr: 381093](https://repository.library.brown.edu/studio/item/bdr: 381093), and [bdr: 381094](https://repository.library.brown.edu/studio/item/bdr: 381094))

When we look at the TTWR site, we get 108 prints and 77 books = 185 objects, but the BDR says that the TTWR collection contains 188 objects, so I think these three jp2 objects are missing entirely from the site.

**Comment by emylonas** [comment]
This has been fixed, in a different iteration
