### ISSUE TITLE
add essay feature to pages

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#140]
needs longer discussion about feature, but need to start roughing it in.

**Comment by lucyvk** [comment]
- "Essays:" links for both books and pages.

**Comment by lucyvk** [comment]
Decided discussion 3/16
- On book page, show links to essays (she will make shorter titles). Clicking on a link will show the first paragraph of the essay (short essays will be only one paragraph). If the essay is longer, there will be a link to "See More," which will take the user to a separate tab on the essay page
- On page detail, do the same thing, but show the paragraph from the beginning (not as a toggle)

**Comment by lucyvk** [comment]
First bullet point pushed to my fork

**Comment by lucyvk** [comment]
Pushed second bullet point to my fork

**Comment by lucyvk** [comment]
Remaining questions
- On a page, should the 1st paragraph of the essay be shown at first, or should it be the same as the book page (as I have it now) and first hidden and then toggled from the title link
- Should "Read More" show up if there is only one paragraph in the essay? The one reason why not might be because the References do not get displayed unless on the full essay page (ex - Bosio essay)

**Comment by lucyvk** [comment]
- Also add "hide" button 
- Experiment on book page with having link disappear and then re-appear

**Comment by lucyvk** [comment]
Above changes pushed to my fork
