### ISSUE TITLE
How are people being looked up

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#146]
It's possible to click on a name in an annotation, and view the biography page for that person. At the bottom of the bio page are the books/pages that the person is related to or mentioned on (in annotations or library metadata)

I found that there was a duplicate person in the people db, and that the two separate biography pages both brought up the same list of book pages. This makes me think that we are looking up which people are related to which page using the name. Perhaps we only save the name from the annotation form. 

However, it's probably not the best way to do it. Can you check on this? 

There are more duplicates than I like to think now that I look at the people list. ugh.

**Comment by lucyvk** [comment]
Ok, I'll take a look!

**Comment by crotger** [comment]
I remember this being an issue when I first made that biography page. Each person has an associated ID, e.g. http://library.brown.edu/projects/rome/people/0087/ , but the list of "pages associated with a person" is generated by searching for annotations that mention a person by name, specifically in the "contributor" field, and then getting the pages that those annotations are on. The code that makes this query is here: [models.py line 36](https://github.com/Brown-University-Library/ttwr/blob/master/models.py#L37) In the BDR search, annotations don't record person IDs, only names. 

The person ID is recorded in the actual MODS file for each annotation, so when we display annotations, we fetch the person ID by downloading the record and get it from there, but for all the pages listed under people we must have decided that making a request for every MODS record was too slow/too complicated (especially for say, Barbault). The code that accomplishes this is in [views.py, line 233](https://github.com/Brown-University-Library/ttwr/blob/master/views.py#L233) (it's a little obscured, but it actually makes an HTTP request for the MODS on line 240). 

We could either ask for that part of the MODS record to be indexed, or we could actually get the MODS for each annotation when we make that biography page. If this was a client-side request (like the red border on annotated pages), it might be more feasible.

**Comment by emylonas** [comment]
thank you Carlos - that's helpful. The ID we record isn't a very useful
one, better if we wait until the library decides to go with an authority
and use that one. Probably already went through that already.

btw, you saw that Birkin updated USEP. you can make a change or I can but
not today. --elli

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by lucyvk** [comment]
- We may decide to stop using the trp_id if it is not currently used due to errors, and instead create a new numeric primary key for the biographies

**Comment by bcail** [comment]
there should already be a Biography.id field that's a numeric primary key - it's created by default in Django.

**Comment by lucyvk** [comment]
Yes there is, I think maybe we can use that field instead of the trp_id's. 

Elli wants to make sure that there is a "uri"-like field that persists if the data is exported and re-imported into another system, which is why a separate trp_id field was create. Perhaps you can offer assurance that the django primary keys would be persistent, in which case the trp_id is unneccessary. 

If the trp_id is necessary, another option would be to copy over the current primary keys into the trp_id field to assure uniqueness.

**Comment by emylonas** [comment]
Yes, that's right - we imported the trp ids when we first made the django system because the earlier system relied on them - they were xml:id's 

I would like to make sure that our people have something that can act like a URI - an ID that will be persistent even if we move to another system in the future, for example. 

If the primary key is able to function that way, then let's go with it. If not,then let's use it in the current db application and clone it into another field that is defined as the "TRP ID".

**Comment by bcail** [comment]
The Biography.id fields are guaranteed to be unique in the current django table.

If the data is ever exported and re-imported into another system, it would be very possible to export these Biography.id fields and import them into the new system.

However, the TRP IDs are used in the annotation objects in the BDR. So, I think it would break things to change TRP IDs if we didn't go through and also update all the annotation objects in the BDR.

If it would be helpful to index the TRP IDs in the annotation objects in the BDR, I think we could do that. Then, searches for annotations could be done by TRP IDs instead of names, if that's helpful. Let me know if you want me to update our indexing.

There's still the issue of duplicate TRP IDs because of leading '0' characters, but I think that was addressed in another bug?

**Comment by lucyvk** [comment]
Yes, I am working on a fix now for the formatting issue.

Sounds like the trp_id's are here to stay due to their use in existing
annotations. Indexing them would be helpful if it's not too much trouble.
